blog/urls.py
from django.urls import path, re_path

from .views import Home, SearchView, DetailPost, contact_us, UpdateComment, DeleteComment

from .views import Home, SearchView, DetailPost, contact_us, like, CreatePost, add_reply
from django.conf.urls import handler404

handler404 = 'blog.views.handl404'


app_name = 'blog'


urlpatterns = [
    path('home/', Home.as_view(), name='Home'),
    path('<int:id>/update/', UpdateComment.as_view(), name='update'),
    path('results/', SearchView.as_view(), name='search'),
    re_path(r'detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', DetailPost, name='detail'),
    path('contact/', contact_us, name='contact'),
    path('<int:id>/delete/', DeleteComment.as_view(), name='delete'),
    re_path(r'like/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', like, name='like_post'),
    path('create_post/', CreatePost, name = 'create_post'),
    path('add_reply/<int:post_id>/<int:comment_id>/', add_reply, name='reply'),
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language = False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATICFILES_DIRS, document_root=settings.STATICFILES_DIRS)

user/urls.py
from .views import User, user_dashboard, signup, CompleteSignUp, follow, unfollow
from django.urls import path, re_path
from django.conf.urls import url
from .feeds import NewPostFollowing
from django.urls import reverse_lazy
from .views import (User,
                    user_dashboard,
                    signup,
                    CompleteSignUp,
                    follower,
                    following,
                    bookmark,
                    user_bookmark
                )
from django.contrib.auth.views import (
                                        LoginView,
                                        LogoutView,
                                    )                                    

app_name = 'user'


urlpatterns = [
    path('userdashboard/<int:user_id>/follow/', follow, name='follow'),
	path('userdashboard/<int:user_id>/unfollow/', unfollow, name='unfollow'),
    path('users/', User.as_view(), name='User'),
    path('signup/', signup, name='signup'),
    path('userdashboard/<int:user_id>/', user_dashboard, name='dashboard'),
    path('profile/',CompleteSignUp, name='create profile'),
    path('login/', LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('followers/<int:id>', follower, name='follower'),
    path('followings/<int:id>', following, name='following'),
    re_path('bookmark/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', bookmark, name='bookmark'),
    path('your_bookmarks/', user_bookmark, name='user_bookmark'),
    path('beats/<int:user_id>/rss/', NewPostFollowing()),    
]

blog/models.py
from django.db import models
from django.utils import timezone
from user.models import Profile
from django.utils.text import slugify
from django.shortcuts import reverse

from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

from extensions.utils import jalali_convertor
from django.contrib.auth.models import User





class Post(models.Model):
    title       = models.CharField(max_length = 50, verbose_name = 'تیتر')
    body        = RichTextUploadingField(blank=True, null=True, verbose_name = 'توضیحات')
    image       = models.ImageField(blank = True, null=True, verbose_name='تصویر')
    create_date = models.DateTimeField(auto_now_add = True, editable=False, verbose_name = 'تاریخ ساخت پست')
    update_date = models.DateTimeField(editable = False, verbose_name = 'تاریخ آپدیت پست')
    user        = models.ForeignKey(User, related_name='user_post',verbose_name = 'پروفایل', on_delete=models.SET_NULL, null = True)
    slug        = models.SlugField(verbose_name = 'اسلاگ', allow_unicode=True)
    publish     = models.BooleanField(default = False)
    likes       = models.ManyToManyField(User, related_name = 'likepost', blank = True)
    tag         = models.TextField(verbose_name = 'برچسب')

    def save(self, *args, **kwargs):
        if not self.create_date:
            self.create_date = timezone.now()

        self.update_date = timezone.now()
        # self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.title} : {self.user}"

    def jalali_date(self):
        return jalali_convertor(self.create_date)

    class Meta:
        ordering = ['-create_date']
        verbose_name = 'پست'
        verbose_name_plural = 'پست‌ها'

blog/forms.py
from django import forms
from blog.models import Post
from django.forms import ModelForm
from comment.models import Comment



class UserCommentForm(forms.Form):
    text = forms.CharField(label='دیدگاه', widget=forms.Textarea(
        attrs={
            'placeholder': '....دیدگاه خود را وارد کنید',
            'autocomplete':'off'
        }
    ))



class CreatePostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'image',
            'body',
            'tag',
        )






class AddReplyForm(ModelForm):
	class Meta:
		model = Comment
		fields = ('text',)

blog/views.py
from user.models import Profile
from django.views.generic.list import ListView
from django.db.models import Count
from django.views.generic.detail import DetailView
from .models import Post
from comment.models import Comment
from .forms import UserCommentForm, CreatePostForm
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django import http
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AddReplyForm
from django.core.cache import cache
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext




CACHE_TTL = getattr(settings, 'CACHE_TTL', 10)

class Home(ListView):
    model = Post
    paginate_by = 2
    template_name = 'blog/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'newposts' in cache:
            newposts = cache.get('newposts')
            starposts = cache.get('starposts')
            context['newposts'] = newposts
            context['starposts'] = starposts
        else:
            newposts = Post.objects.filter(publish=True).order_by('create_date__hour')
            starposts = Post.objects.annotate(like_count=Count('likes')).order_by('-like_count')[:3]
            context['newposts'] = newposts
            context['starposts'] = starposts
            cache.set('newposts', newposts, timeout=CACHE_TTL)
            cache.set('starposts', starposts, timeout=CACHE_TTL)
        return context




class SearchView(ListView):
    model = Post
    template_name = 'blog/searchresult.html'
    context_object_name = 'all_search_results'

    def get_queryset(self):
        result = super(SearchView, self).get_queryset()
        query = self.request.GET.get('search')
        if query:
            postresult = Post.objects.filter(title__contains=query)
            result = postresult
        else:
            result = None
        return result



def DetailPost(request, id, slug):
    if 'post' in cache:
        post = cache.get('post')
        comments = cache.get('comments')
        total_likes = cache.get('total_likes')
    else:
        post = Post.objects.get(id=id, slug=slug)  
        # comments = Comment.objects.all().order_by('-create_date')
        comments = Comment.objects.filter(post=post).order_by('-create_date')
        total_likes = post.total_likes()

        cache.set('post', post, timeout=CACHE_TTL)
        cache.set('comments', comments, timeout=CACHE_TTL)
        cache.set('total_likes', total_likes, timeout=CACHE_TTL)


    Liked = False
    bookmarked = False
    if post.likes.filter(id = request.user.id).exists():
        Liked = True
    
    if request.user.is_authenticated:
        profile = get_object_or_404(Profile, id = request.user.id)
        if profile.bookmark.filter(id = post.id).exists():
            bookmarked = True
    if request.method == "POST" and request.user.is_authenticated:
        form = UserCommentForm(request.POST)
        if form.is_valid():
             
            cd   = form.cleaned_data
            c1   = Comment.objects.create(post=post, user = request.user, text=cd['text'])
            c1.save()
            messages.success(request, 'دیدگاه شما با موفقیت ثبت شد')
            # return http.HttpResponseRedirect('')
            return redirect('blog:detail', id=post.id,slug=post.slug)
    
    elif request.method == "POST" and not request.user.is_authenticated:
        messages.error(request,"شما ابتدا باید لاگین کنید")
        form = UserCommentForm()
    else:
        form = UserCommentForm()
        


    context = {
        'post' : post,
        'comments': comments,
        'form': form,
        'total_likes' : total_likes,
        'Liked' : Liked,
        'bookmarked' : bookmarked,
    }
    return render(request, 'blog/PostDetail.html', context)





def add_reply(request, post_id, comment_id):
    post    = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = AddReplyForm(request.POST)
        if form.is_valid():
            rep_com = form.save(commit=False)
            rep_com.user = request.user
            rep_com.post = post
            rep_com.username_reply = comment.user.username
            rep_com.is_reply = True
            rep_com.save()
            messages.success(request, 'دیدگاه شما با موفقیت ارسال شد', 'success')
            return redirect('blog:detail', id=post.id,slug=post.slug)
    else:
        form = AddReplyForm()

    context = {
        'form': form
    }
    return render(request, 'blog/add_reply.html', context)
            








@login_required
def like(request, id, slug):
    pk = request.POST.get('post_id')
    post = get_object_or_404(Post, id = pk)
    if post.likes.filter(id = request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('blog:detail', id=id, slug=slug)



def contact_us(request):
    return render(request, 'blog/contact.html')



class UpdateComment(UpdateView):
    model = Comment
    fields = ['text']
    template_name = 'blog/update_comment.html'
    
    def get_object(self):
        return get_object_or_404(Comment.objects.filter(id=self.kwargs.get("id")))


    def get_success_url(self):
        c = Comment.objects.get(id=self.kwargs.get("id"))
        id_post = c.post.id
        slug_post = c.post.slug
        return reverse_lazy('blog:detail', kwargs={'id': id_post, 'slug': slug_post})



    


class DeleteComment(DeleteView):
    model = Comment
    template_name = 'blog/delete_comment.html'


    def get_object(self):
        return get_object_or_404(Comment.objects.filter(id=self.kwargs.get("id")))

    def get_success_url(self):
        c = Comment.objects.get(id=self.kwargs.get("id"))
        id_post = c.post.id
        slug_post = c.post.slug
        return reverse_lazy('blog:detail', kwargs={'id': id_post, 'slug': slug_post})







@login_required
def CreatePost(request):
    if request.method == 'POST':
        post_form = CreatePostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit = False)
            post.user = request.user
            post_form.save()
            messages.success(request, 'پست با موفقیت ساخته شد')
            return redirect('blog:Home')
    else:
        post_form = CreatePostForm()
    return render(request, 'blog/CreatePost.html', {'form_post': post_form})



def handl404(request, exception, template_name="404.html"):
    response = render_to_response(template_name)
    response.status_code = 404
    return response

blog/templates/blog/CreatePost.html
{% extends 'base.html'%}
{% load static %}


{% block content %}

<form method="POST">
    {% csrf_token %}
    <div>
        <!-- Title -->
        {{ form_post.as_p }}
    </div>
    <div>
        {{ form_post.media }}
    </div>
    <br>
        <input type="submit" value="Create">
    </br>
</form>

{% endblock %}

blog/templates/blog/PostDetail.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'blog/css/comment.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
{% endblock %}



{% block content %}
<div class="searchdiv">
    <form method="GET" action="{% url 'blog:search' %}" class="search-container">
        <input type="text" name="search" placeholder="Search..." class="search-input">
            <a href="#" class="search-btn">
                <i class="fas fa-search"></i>      
            </a>
    </form>
    </div>


<form method="POST" action="{% url 'user:bookmark' post.id post.slug %}">
    {% csrf_token %}
    {% if not bookmarked %}
        <button type="submit", name="post_id", value = "{{ post.id }}" class="far fa-bookmark"></button>
    {% else %}
        <button type="submit", name="post_id", value = "{{ post.id }}" class="fas fa-bookmark"></button>
    {% endif %}
</form>
<article>
    <h1>{{post.title}}</h1>
    <h3>{{post.jalali_date}}</h3>
    <h4>نوشته شده توسط <a href="{% url 'user:dashboard' post.user.id %}">{{ post.user.username }}</a></h4>
    <hr>
    <p>{{post.body|safe}}</p>
    
    <form method="POST" action="{% url 'blog:like_post' post.id post.slug %}">
        {% csrf_token %}
        {% if Liked %}
            <button type="submit", name="post_id", value = "{{ post.id }}" class="btn btn_danger btn_sm">Unlike</button>
            {{ total_likes }} Likes{{ total|pluralize }}
        {% else %}
            <button type="submit", name="post_id", value = "{{ post.id }}" class="btn btn_primary btn_sm">Like</button>
            {{ total_likes }} Likes{{ total|pluralize }}
        {% endif %}
    </form>
</article>

<div >
    <center>
<form method="POST" class="send-comment-box">
    {%csrf_token%}
    <p>{{form}}</p>
    <input style="color: red;" class="send-btn" type="Submit" value="ارسال دیدگاه">
</form>
</center>
</div>

<br><br>
<h1 class="title">Comments</h1>
{% with total=comments.count %}
<p>This post has {{ total }} comment{{ total|pluralize }}</p>
{% endwith %}



<div class="base-comment">
    {%for comment in comments%}
    
    <div class="box">
    <img src="{{ comment.user.profile.image.avatar.url }}" class="profile">
    <p  class="comment-header"><a href="{%url 'user:dashboard' user.id%}">{{comment.user.username}} </a></p>
    <hr>
    {%if comment.is_reply == True%}
    <p  class="comment-body"> <span>@{{comment.username_reply}}</span> <span>{{comment.text}}</span> <a class="comment-reply" href="{%url 'blog:reply' post.id comment.id%}">reply</a> 
    


    {% if request.user == comment.user %} <a class="comment-update" href="{%url 'blog:update' comment.id %}">update</a> 
    <a class="comment-delete" href="{%url 'blog:delete' comment.id %}">delete</a>{%endif%} </p>
    


    {%else%}
    <p  class="comment-body">{{comment.text}} <a class="comment-reply" href="{%url 'blog:reply' post.id comment.id%}">reply</a>


        {% if request.user == comment.user %} <a class="comment-update" href="{%url 'blog:update' comment.id %}">update</a>
        <a class="comment-delete" href="{%url 'blog:delete' comment.id%}">delete</a>
        {%endif%}</p>


    {%endif%}
</div>
    {%endfor%}
{% endblock %}

blog/templates/blog/add_reply.html
{%extends 'base.html'%}
{%load static%}


{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
{% endblock %}

{%block content%}
<form method="POST">
    {%csrf_token%}
    {{form}}
    <input type="Submit" value="send">
</form>
{%endblock%}

blog/templates/blog/contact.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'blog/css/contact.css' %}"/>
  <script src="{% static 'blog/js/contact.js' %}" type="text/javascript"></script>

</head>

<div class="nav">
  <a href="{% url 'blog:Home' %}" class="menu-activator"><i class="ion-ios-more"></i></a>
  <i class="ion-cube"></i>
  <a href="{% url 'blog:Home' %}" class="white link"><i class="ion-ios-redo-outline"></i><i class="ion-ios-redo hidden"></i></a>
</div>
<div class="container">
  <div class="inner">
    <div class="panel panel-left">
      <div class="panel-content">
        <div class="image-background">
        </div>
      </div>
    </div>
    <div class="panel panel-right">
      <div class="panel-content">
        <div class="form">
          <h1>SAY HELLO TO OPTIVAS GROUP</h1>
          <div class="group">      
            <input type="text" required>
            <span class="highlight"></span>
            <label>Your name</label>
          </div>
          <div class="group">      
            <input type="text" required>
            <span class="highlight"></span>
            <label>Your email</label>
          </div>
          <div class="group">      
            <input type="text" required>
            <span class="highlight"></span>
            <label>Your comment</label>
          </div>
          <a class="send-btn">Send</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="menu"></div>

blog/templates/blog/delete_comment.html
{%extends 'base.html'%}

{%block content%}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }} : {{object.text}} comment?</p>
    <input type="submit" value="Delete">
</form>
{%endblock%}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}



{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
{% endblock %}




{% block content %}
        
    <div class="searchdiv">
    <form method="GET" action="{% url 'blog:search' %}" class="search-container">
        <input type="text" name="search" placeholder="Search..." class="search-input">
            <a href="#" class="search-btn">
                <i class="fas fa-search"></i>      
            </a>
    </form>
    </div>
    <div id="sline">
        <div class="sdline"></div>
        <h1>NEW POSTS</h1>
        <div class="sdline"></div>
    </div>

    <div id="latestp">
        {% for item in newposts %}
            <article>
                <h1> <a href="{% url 'blog:detail' item.id item.slug %}"> {{ item.title }}</a></h1>
                <p>{{ item.description|truncatewords:50 }}</p>
                <a href="{% url 'blog:detail' item.id item.slug %}" class="rm">Read More</a>
            </article>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/reply_comment.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="send" class="btn btn-primary">
    </form>
{% endblock %}

blog/templates/blog/searchresult.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% for post in all_search_results %}
        <h3>{{ post.title }}</h3>
        <p>{{ post.description }}</p>
        <img src="{{ post.images.image1.url }}">
    {% empty %}
        <h2>No results found</h2>
    {% endfor %}
{% endblock %}

blog/templates/blog/update_comment.html
{%extends 'base.html'%}
{%load static%}


{% block head %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
{% endblock %}


{%block content%}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{%endblock%}