blog/urls.py
from django.urls import path, re_path

from .views import Home, SearchView, DetailPost, contact_us, UpdateComment, DeleteComment

from .views import Home, SearchView, DetailPost, contact_us, like, CreatePost, add_reply
from django.conf.urls import handler404

handler404 = 'blog.views.handl404'


app_name = 'blog'


urlpatterns = [
    path('home/', Home.as_view(), name='Home'),
    path('<int:id>/update/', UpdateComment.as_view(), name='update'),
    path('results/', SearchView.as_view(), name='search'),
    re_path(r'detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', DetailPost, name='detail'),
    path('contact/', contact_us, name='contact'),
    path('<int:id>/delete/', DeleteComment.as_view(), name='delete'),
    re_path(r'like/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', like, name='like_post'),
    path('create_post/', CreatePost, name = 'create_post'),
    path('add_reply/<int:post_id>/<int:comment_id>/', add_reply, name='reply'),
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language = False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATICFILES_DIRS, document_root=settings.STATICFILES_DIRS)

user/urls.py
from .views import User, user_dashboard, signup, CompleteSignUp, follow, unfollow
from django.urls import path, re_path
from django.conf.urls import url
from .feeds import NewPostFollowing
from django.urls import reverse_lazy
from .views import (User,
                    user_dashboard,
                    signup,
                    CompleteSignUp,
                    follower,
                    following,
                    bookmark,
                    user_bookmark
                )
from django.contrib.auth.views import (
                                        LoginView,
                                        LogoutView,
                                    )                                    

app_name = 'user'


urlpatterns = [
    path('userdashboard/<int:user_id>/follow/', follow, name='follow'),
	path('userdashboard/<int:user_id>/unfollow/', unfollow, name='unfollow'),
    path('users/', User.as_view(), name='User'),
    path('signup/', signup, name='signup'),
    path('userdashboard/<int:user_id>/', user_dashboard, name='dashboard'),
    path('profile/',CompleteSignUp, name='create profile'),
    path('login/', LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('followers/<int:id>', follower, name='follower'),
    path('followings/<int:id>', following, name='following'),
    re_path('bookmark/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', bookmark, name='bookmark'),
    path('your_bookmarks/', user_bookmark, name='user_bookmark'),
    path('beats/<int:user_id>/rss/', NewPostFollowing()),    
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import (
                        TelegramValidator,
                        TwitterValidator,
                        InstagramValidator,
                        TwitterValidator,
                        LinkedinValidator,
                        GithubValidator,
                        GitlabValidator,
                        )

class UserImage(models.Model):
    avatar       = models.ImageField(blank=True, null=True,\
                                        upload_to='avatar_pic',\
                                        verbose_name = 'آواتار',
                                        default = 'avatar_pic/profile.png'
                                        )
    header_image = models.ImageField(blank=True, null=True,\
                                        upload_to='header_pic',\
                                        verbose_name = 'تصویر هدر',
                                        default = 'header_pic/header.png'
                                        )

    class Meta:
        verbose_name = 'تصویر کاربر'
        verbose_name_plural = 'تصاویر کاربر'




class social(models.Model):
    github    = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'گیت‌هاب', validators=[GithubValidator,]
                                )
    gitlab    = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'گیت‌‌لب', validators=[GitlabValidator,]
                                )
    instagram = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'اینستاگرام', validators=[InstagramValidator,]
                                )
    tweeter   = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'تويیتر', validators=[TwitterValidator,]
                                )
    linkedin  = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'لینکدین', validators=[LinkedinValidator,]
                                )
    telegram  = models.CharField(max_length=50, null=True, blank=True,
                                verbose_name = 'تلگرام', validators=[TelegramValidator,]
                                )

    class Meta:
        verbose_name = 'شبکه اجتماعی'
        verbose_name_plural = 'شبکه‌های اجتماعی'





class Profile(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name = 'کاربر', related_name= 'profile')
    image        = models.OneToOneField(UserImage, on_delete=models.SET_NULL, null=True, blank=True, verbose_name = 'تصویر')
    phone_number = models.CharField(max_length=50, verbose_name='شماره تماس')
    biography    = models.TextField(max_length=250, verbose_name='بیوگرافی', null=True, blank=True)
    social       = models.OneToOneField(social, on_delete=models.SET_NULL, null=True, blank=True, verbose_name = 'شبکه اجتماعی')
    bookmark     = models.ManyToManyField('blog.Post', related_name='bookmark', blank=True, verbose_name = 'بوک مارک')

    class Meta:
        verbose_name = 'پروفایل'
        verbose_name_plural = 'پروفایل‌ها'

    def __str__(self):
        return self.user.username


class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower', verbose_name='فالوور', blank=True)
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following', verbose_name='فالووینک', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'ارتباط'
        verbose_name_plural = 'ارتباطات'


    def __str__(self):
        return f'{self.from_user} following {self.to_user}'

user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, social, UserImage
from captcha.fields import CaptchaField



class SignUpForm(UserCreationForm):
    email   = forms.EmailField(max_length=254, help_text='requierd')
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2', 
            )

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = (
            'phone_number',
            'biography',
            )


class ImageProfileForm(ModelForm):

    class Meta:
        model = UserImage
        fields = (
            'avatar',
            'header_image',
            )


class SocialProfileForm(ModelForm):
    class Meta:
        model = social
        fields = '__all__'

user/views.py
from django.contrib.auth.models import User
from django.views.generic.list import ListView
from blog.models import Post
from django.shortcuts import get_object_or_404, render
from .models import Profile
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import SignUpForm, ProfileForm, SocialProfileForm, ImageProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as UserModel
from .models import Relation
from django.http import JsonResponse



class User(ListView):
    model = Post
    paginate_by = 6
    template_name = 'user/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["postuser"] = Post.objects.filter(user__user=self.request.user)
        print(context)
        return context




def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'اکانت با موفقیت ساخته شد')
            return redirect('blog:Home')
    else:
        form = SignUpForm()
    return render(request, 'user/signup.html', {'form': form})




@login_required
def CompleteSignUp(request):
    if request.method == 'POST':
        profile = get_object_or_404(Profile, id=request.user.id)
        profile_form = ProfileForm(request.POST,instance=profile)
        image_profile_form = ImageProfileForm(request.POST, request.FILES,instance=profile.image)
        social_profile_form = SocialProfileForm(request.POST, instance=profile.social)
        if profile_form.is_valid() and image_profile_form.is_valid() and social_profile_form.is_valid():
            profile = profile_form.save(commit=False)
            social  = social_profile_form.save()
            images  = image_profile_form.save()
            profile.user = request.user
            profile.social = social
            profile.image = images
            profile.save()
            messages.success(request, 'پروفایل با موفقیت کامل شد')
            return redirect('blog:Home')
    else:
        profile = get_object_or_404(Profile, id = request.user.id)
        profile_form = ProfileForm(
                                    initial={
                                        'phone_number': profile.phone_number,
                                        'biography':profile.biography
                                        }
                                )
        if profile.image:
            image_profile_form = ImageProfileForm(
                                                initial={
                                                    'avatar':profile.image.avatar,
                                                    'header_image':profile.image.header_image
                                                }
                                        )
        else:
            image_profile_form = ImageProfileForm()
        if profile.social:
            social_profile_form = SocialProfileForm(
                                                initial={
                                                    'github':profile.social.github,
                                                    'gitlab':profile.social.gitlab,
                                                    'instagram':profile.social.instagram,
                                                    'tweeter':profile.social.tweeter,
                                                    'linkedin':profile.social.linkedin,
                                                    'telegram':profile.social.telegram,
                                                }
                                            )
        else:
            social_profile_form = SocialProfileForm()
        
    return render(request, 'user/createprofile.html', {'form_p': profile_form, 'form_i': image_profile_form, 'form_s': social_profile_form})



def user_dashboard(request, user_id):
    user = get_object_or_404(UserModel, id=user_id)
    posts = Post.objects.filter(user_id = user.id)
    self_panel = False
    is_following = False
    relation = Relation.objects.filter(from_user = request.user.id, to_user=user)
    if relation.exists():
        is_following = True
    if request.user.id == user_id:
        self_panel = True
    x = {'user': user, 'posts': posts, 'self_dash': self_panel, 'is_following': is_following}
    return render(request, 'user/dashboard.html',
                  {'user': user, 'posts': posts, 'self_dash': self_panel, 'is_following': is_following})






# ============================================== follow ========================================================
@login_required
def follow(request, user_id):
	if request.method == 'POST':
		user_id = request.POST['user_id']
		following = get_object_or_404(UserModel, pk=user_id)
		check_relation = Relation.objects.filter(from_user=request.user, to_user=following)
		if check_relation.exists():
			return JsonResponse({'status':'exists'})
		else:
			Relation(from_user=request.user, to_user=following).save()
			return JsonResponse({'status':'ok'})

# ============================================= unfollow ======================================================
@login_required
def unfollow(request,user_id):
	if request.method == 'POST':
		user_id = request.POST['user_id']
		following = get_object_or_404(UserModel, pk=user_id)
		check_relation = Relation.objects.filter(from_user=request.user, to_user=following)
		if check_relation.exists():
			check_relation.delete()
			return JsonResponse({'status':'ok'})
		else:
			return JsonResponse({'status':'notexists'})



@login_required
def bookmark(request, id, slug):
    pk = request.POST.get('post_id')
    post = get_object_or_404(Post, id = pk)
    profile = get_object_or_404(Profile, id = request.user.id)
    if profile.bookmark.filter(id =post.id).exists():
        profile.bookmark.remove(post)
    else:
        profile.bookmark.add(post)
    return redirect('blog:detail', id=id, slug=slug)




@login_required
def user_bookmark(request):
    bookmark = request.user.profile.bookmark.all()
    return render(request, 'user/bookmark.html',{'bookmark':bookmark})
    


def follower(request, id):
    user = get_object_or_404(Profile, user_id=id)
    followers = user.followers.all()
    return render(request, 'user/follower.html', {'followers':followers,})

def following(request, id):
    user = get_object_or_404(Profile, user_id=id)
    following = user.following.all()
    return render(request, 'user/following.html', {'following':following,})

user/templates/user/bookmark.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
    Bookmark
{% endblock %}

{% block content %}
    <p>
        Your bookmarks
    </p>
    {% for item in bookmark %}
        <article>
            <h1> <a href="{% url 'blog:detail' item.id item.slug %}"> {{ item.title }}</a></h1>
            <p>{{ item.description|truncatewords:50 }}</p>
            <a href="{% url 'blog:detail' item.id item.slug %}" class="rm">Read More</a>
        </article>
    {% endfor %}

{% endblock %}

user/templates/user/createprofile.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form_p.biography }}
        biography 
    </div>
    <div>
        {{ form_p.phone_number }}
        phone_number
    </div>
    <div>
        {{ form_i.avatar }}
        avatar
    </div>
    <div>
        {{ form_i.header_image }}
        header
    </div>
    <div>
        {{ form_s.telegram }}
        telegram id
    </div>
    <div>
        {{ form_s.github }}
        github id
    </div>
    <div>
        {{ form_s.instagram }}
        instagram id
    </div>
    <div>
        {{ form_s.linkedin }}
        linkedin id
    </div>
    <div>
        {{ form_s.gitlab }}
        gitlab id
    </div>
    <div>
        {{ form_s.tweeter }}
        tweeter id
    </div>
    <br>
        <input type="submit" value="Register">
    </br>
    
</form>
    {% for field in form_s %}
        {% for error in field.errors %}
        <p style="color: rgba(255, 0, 0, 0.678)">{{ error }}</p>
        {% endfor %}
    {% endfor %}

{% endblock %}

user/templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ user.username }} Profile {% endblock %}




{% block js_files %}
<script src="{% static 'user/script.js' %}"></script>
{% endblock %}




{% block content %}

{% block head %}
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}"/>
{% endblock %}

<h1 class="text-center">{{ user.username|capfirst }}</h1>
<br>

<div class="main-container">
        {{ user.profile }}
        {% if user.profile.image.header_image %}
            <img src="{{ user.profile.image.header_image.url }}" class="header">
        {% else %}
            <img src={% static "img/header.png" %} class="header">
        {% endif %}  
        {% if user.profile.image.avatar %}
            <img src="{{ user.profile.image.avatar.url }}" class="profile">
        {% else %}
        <img src={% static "img/profile.png" %} class="profile">
        {% endif %}
    <div class="content">
      
    </div>
</div>


{% if self_dash %}
    <br><a href="{% url 'blog:create_post' %}"><i class="fas fa-plus fa-3x"> </i>ADD POST</a></br>
    <br><a href="{% url 'user:create profile' %}"><i class="fas fa-edit fa-2x"></i>EDIT PROFILE</a></br>
{% endif %}



<p class='bio'>BIOGRAPHY</p>
<p class="text-center">{{ user.profile.biography | linebreaks }}</p>

<br><br>

{% if user.profile.social %}
    <p class='bio'>Social Networks</p>

    {% if user.profile.social.github %}              <!--github-->     
        <a href="http://{{ user.profile.social.github }}" target = _blank style="margin: 5px;"><i class="fab fa-github fa-2x"></i></a>
    {% endif %}

    {% if user.profile.social.gitlab %}              <!--gitlab-->
        <a href="http://{{ user.profile.social.gitlab}}" target = _blank style="margin: 5px;"><i class="fab fa-gitlab fa-2x"></i></a>
    {% endif %}

    {% if user.profile.social.instagram %}           <!--instagram-->
        <a href="http://{{ user.profile.social.instagram }}" target = _blank style="margin: 5px;"><i class="fab fa-instagram fa-2x"></i></a>
    {% endif %}

    {% if user.profile.social.tweeter %}             <!--tweeter-->
        <a href="http://{{ user.profile.social.tweeter }}" target = _blank style="margin: 5px;"><i class="fab fa-twitter fa-2x"></i></a>
    {% endif %}

    {% if user.profile.social.linkedin %}             <!--linkedin-->
        <a href="http://{{user.profile.social.linkedin }}" target = _blank style="margin: 5px;"><i class="fab fa-linkedin-in fa-2x"></i></a>
    {% endif %}
    
    {% if user.profile.social.telegram %}             <!--telegram-->
        <a href='http://{{ user.profile.social.telegram }}' target = _blank style="margin: 5px;"><i class="fab fa-telegram-plane fa-2x"></i></a>
    {% endif %}

{% endif %}















{% if request.user.id != user.id and not is_following %}
<button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-primary text-center mx-auto">follow</button>
{% elif request.user.id != user.id and is_following %}
<button id="following_btn" data-id="{{ user.id }}" style="display:block" class="btn btn-warning text-center mx-auto">unfollow</button>
{% endif %}



















<br/><br/><br/>
















{% if posts is not empty %}
    <h1 class="center" >posts</h1>
{% endif %}

{% for post in posts %}
    <div class="card">
        <a class='title' href="{% url 'blog:detail' post.id post.slug %}"><p>{{ post.title }}</p></a>
        <p class="card-body">{{ post.body | safe | truncatewords:50}}</p>
        <a href="{% url 'blog:detail' post.id post.slug %}" class="rm">Read More</a>
    </div>
    <br><hr><br>
{% empty %}
    <p>This user has no posts</p>
{% endfor %}

{% endblock %}

user/templates/user/follower.html
{% extends 'base.html' %}
{% load static %}



{% block title %}
Fallowers
{% endblock %}
{% block content %}
<p>
    followers:
</p>

{% for item in followers %}
    <p>
        {{ item.username }}
    </p>
{% endfor %}

{% endblock %}

user/templates/user/following.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Fallowings
{% endblock %}
{% block content %}
<p>
    following:
</p>

{% for item in following %}
    <p>
        {{ item.username }}
    </p>
{% endfor %}

{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

user/templates/user/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        <p>
          <span>
            {{ field.label_tag }}
          </span>
          <span>
            {{ field }}
          </span>
          
        </p>
        
          
        {% if field.help_text %}
          <small style="color: rgb(104, 175, 180)">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: rgba(187, 11, 11, 0.678)">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

user/templates/user/user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--__--__--__--__--  M A I N   C O N T E N T  --__--__--__--___--__--__-->

<section>
			
    <!--__--__--__-- A R T I C L E S --__--__--__--__-->

    <div id="articles">
        {% for item in postuser %}
        <article>
            <h1><a href="singlepost.html"> {{ item.title }} </a></h1>
            <h2>Posted By: <a href="#">Admin</a> On {{ item.create_date }}.</h2>
            <img src="images/a1.jpg" alt="" />
            <p> {{ item.description|truncatewords:50 }} <a class="continue" href="">Continue Reading</a></p>
        </article>
        {% endfor %}
    </div>

</section>

{% endblock %}