blog/urls.py
from django.urls import path, re_path

from .views import Home, SearchView, DetailPost, contact_us, UpdateComment, DeleteComment

from .views import Home, SearchView, DetailPost, contact_us, like, CreatePost, add_reply
from django.conf.urls import handler404

handler404 = 'blog.views.handl404'


app_name = 'blog'


urlpatterns = [
    path('home/', Home.as_view(), name='Home'),
    path('<int:id>/update/', UpdateComment.as_view(), name='update'),
    path('results/', SearchView.as_view(), name='search'),
    re_path(r'detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', DetailPost, name='detail'),
    path('contact/', contact_us, name='contact'),
    path('<int:id>/delete/', DeleteComment.as_view(), name='delete'),
    re_path(r'like/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', like, name='like_post'),
    path('create_post/', CreatePost, name = 'create_post'),
    path('add_reply/<int:post_id>/<int:comment_id>/', add_reply, name='reply'),
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language = False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATICFILES_DIRS, document_root=settings.STATICFILES_DIRS)

user/urls.py
from .views import User, user_dashboard, signup, CompleteSignUp, follow, unfollow
from django.urls import path, re_path
from django.conf.urls import url
from .feeds import NewPostFollowing
from django.urls import reverse_lazy
from .views import (User,
                    user_dashboard,
                    signup,
                    CompleteSignUp,
                    follower,
                    following,
                    bookmark,
                    user_bookmark
                )
from django.contrib.auth.views import (
                                        LoginView,
                                        LogoutView,
                                    )                                    

app_name = 'user'


urlpatterns = [
    path('userdashboard/<int:user_id>/follow/', follow, name='follow'),
	path('userdashboard/<int:user_id>/unfollow/', unfollow, name='unfollow'),
    path('users/', User.as_view(), name='User'),
    path('signup/', signup, name='signup'),
    path('userdashboard/<int:user_id>/', user_dashboard, name='dashboard'),
    path('profile/',CompleteSignUp, name='create profile'),
    path('login/', LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('followers/<int:id>', follower, name='follower'),
    path('followings/<int:id>', following, name='following'),
    re_path('bookmark/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', bookmark, name='bookmark'),
    path('your_bookmarks/', user_bookmark, name='user_bookmark'),
    path('beats/<int:user_id>/rss/', NewPostFollowing()),    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title> 
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nivo_slider.css' %}" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'css/default/default.css' %}" type="text/css" media="screen"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/jquery.nivi.slider.pack.js' %}" type="text/javascript"></script>
    <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
    {% block head %}
    {% endblock %}
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body id="blog">

    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
        </ul>
    {% endif %}

<div id="wrapper">
    <!--__--__--__--__--__--  L O G O  &   N A V    B A R --__--___--__--__--__-->
    <header>
        <div id="logo">
            <h1>PORTFOLIO <span id="ii">II</span> <span id="srt">OPTIVAS</span></h1>
            <div id="tagline">
            </div>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'blog:Home' %}" id="homenav">Home</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="about.html">About</a></li>
                <div class="dropdown">
                    <button id="dropbtn">Login | Logout</button>
                    <div class="dropdown-content" id="DropDownContent">
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'user:logout' %}">Logout</a>
                        <a href="{% url 'user:dashboard' request.user.id %}">Dashboard</a>
                        {% else %}
                        <a href="{% url 'user:login' %}">Login</a>
                        <a href="{% url 'user:signup' %}">Register</a>
                        {% endif %}f
                    </div>
                </div>
            </ul>
        </nav>
    </header>
    <!--__--__--__--__--  M A I N   C O N T E N T  --__--__--__--___--__--__-->
    <section>
        {% block content %}
        {% endblock %}
        <!--__--__--__--  S I D E B A R --__--__--__--__-->
    </section>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
{% block js_files %}{% endblock %}
</body>
</html>
		
		
			